version: '3'
services:
  bot:
    build: .
    volumes:
      - "/mnt/vols/nadeko/NadekoBot.db:/opt/NadekoBot/NadekoBot.db"
      - "/mnt/vols/nadeko-creds/credentials.json:/opt/NadekoBot/src/NadekoBot/credentials.json"
